### ISSUE TITLE
Public HyperswarmServer?

### ISSUE THREAD

**Issue by KyleMaas** [RangerMauve/hyperswarm-web#14]
Is it possible you could run a public HyperswarmServer?  I'd like to try to add hyperswarm-web into multiserver-dht so that it could be used from a browser, but I don't have anywhere to point it so I can test it and make sure it works before I do a pull request.

**Comment by RangerMauve** [comment]
Yeah, there's actually some public servers that come pre-configered in hyperswarm-web here: https://github.com/RangerMauve/hyperswarm-web/blob/master/index.js#L6

Do note that I have no guarantees for uptime on them, so if you're making an app it's still advised to host your own.

**Comment by KyleMaas** [comment]
Excellent.  Good to know.  Thanks!
