### ISSUE TITLE
Decoded message is not valid

### ISSUE THREAD

**Issue by itsdeka** [RangerMauve/hyperswarm-web#17]
I am stuck trying to setup the hypercore-web server for this project (https://github.com/itsdeka/dazaar-react-starter)

Server looks online

![11 (36)](https://user-images.githubusercontent.com/31732142/118393158-e66b8b00-b63d-11eb-8e11-45a9cb75d7f9.png)

but when I interact with it from the react app it crashes

![11 (37)](https://user-images.githubusercontent.com/31732142/118393168-f4b9a700-b63d-11eb-9eff-eab42d2e81a7.png)

**Comment by itsdeka** [comment]
It works locally, it does not when it is server by nginx with wss

**Comment by RangerMauve** [comment]
Thanks for the bug report.

Sounds like it might be an nginx issue. 🤔

Here's a config that has worked for me in the past:

```
server {
  server_name mydatstore.my-pinning-server.com;

  location / {
    proxy_pass http://localhost:3472;
    proxy_set_header    Host            $host;
    proxy_set_header    X-Real-IP       $remote_addr;
    proxy_set_header    X-Forwarded-for $remote_addr;
    port_in_redirect    off;
    proxy_http_version  1.1;
    proxy_set_header    Upgrade         $http_upgrade;
    proxy_set_header    Connection      "Upgrade";
  }

    listen 80;
    listen [::]:80;

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    
    # ... Certbot managed cerificate stuff down here ...#
}
```

Does that help?

**Comment by itsdeka** [comment]
Great, it works!
Thank you very much for your help

**Comment by RangerMauve** [comment]
Glad I could help.

A PR to the README that clarifies this would also be appreciated. 😁
