### ISSUE TITLE
geut-webrtc-signal.herokuapp.com is down,and with it almost any app based on hyperswarm-web

### ISSUE THREAD

**Issue by pasqui23** [RangerMauve/hyperswarm-web#4]
Please use a more comprehensive list of servers for DEFAULT_WEBRTC_BOOTSTRAP

**Comment by RangerMauve** [comment]
Hey! Thanks for the patience, I've been stretched a bit thin with other open source things on my mind.

Is this still a problem?  cc @tinchoz49 @dpaez Are you folks still maintaining it?

I'd be down for PRs to add more active bootstrap servers. I think @sammacbeth had one for Cliqz at some point.

**Comment by tinchoz49** [comment]
Hey @RangerMauve yes but we don't pay for the heroku server and we reach the limit per month :(

**Comment by sammacbeth** [comment]
> I'd be down for PRs to add more active bootstrap servers. I think @sammacbeth had one for Cliqz at some point.

Feel free to use https://signal.dat-web.eu/ . If the traffic level is acceptable for a signal vps, I can keep this running long term.

**Comment by RangerMauve** [comment]
@sammacbeth  Sweet, we'll add it to the list after #5 lands. 😁 Would you like your server to be earlier or later in the list?

**Comment by tinchoz49** [comment]
Something important to add is that the new version of discovery-swarm-webrtc stop using socket.io. Now we have clean websockets on top of [socket-signal](https://github.com/geut/socket-signal) so it's a breaking change for the server signals and the client.

**Comment by RangerMauve** [comment]
Ah, good point. I've released it in hyperswarm-web@2.0.0

Hopefully this will help with stability somewhat. 😁

**Comment by tinchoz49** [comment]
Yes, I hope so :)

**Comment by sammacbeth** [comment]
> @sammacbeth Sweet, we'll add it to the list after #5 lands. 😁 Would you like your server to be earlier or later in the list?

Just updated this to run the latest version of `discovery-swarm-webrtc`'s server. I don't mind where on the list this lives, I don't imagine there would be enough traffic to cause issues for the server.

**Comment by tinchoz49** [comment]
thank you @sammacbeth !
